version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: platziflix
      POSTGRES_PASSWORD: platziflix
      POSTGRES_DB: platziflix
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    command: uv run uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./specs:/app/specs
    environment:
      DATABASE_URL: postgresql+psycopg2://platziflix:platziflix@db:5432/platziflix
    depends_on:
      - db

volumes:
  db_data: 